"""initial_schema

Revision ID: f91f5b9faf34
Revises: 
Create Date: 2026-01-14 13:33:10.296563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91f5b9faf34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False, comment='15-digit GST Identification Number'),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True, comment='Path to business logo file'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='Business website or profile URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=True)
    op.create_table('invoice_number_sequences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_type', sa.String(length=10), nullable=False, comment="'topmate' or 'user'"),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='User ID for user-specific sequences'),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_type', 'user_id', name='uq_sequence_type_user')
    )
    op.create_index(op.f('ix_invoice_number_sequences_id'), 'invoice_number_sequences', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=10), nullable=False, comment="'topmate' or 'user'"),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='User ID who generated the invoice'),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_gstin', sa.String(length=15), nullable=False),
    sa.Column('seller_address', sa.Text(), nullable=False),
    sa.Column('seller_pincode', sa.String(length=6), nullable=False),
    sa.Column('seller_state', sa.String(length=2), nullable=False),
    sa.Column('seller_phone', sa.String(length=15), nullable=True),
    sa.Column('seller_email', sa.String(length=100), nullable=True),
    sa.Column('seller_logo', sa.String(length=500), nullable=True),
    sa.Column('seller_website', sa.String(length=200), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=False),
    sa.Column('buyer_pincode', sa.String(length=6), nullable=False),
    sa.Column('buyer_state', sa.String(length=2), nullable=False),
    sa.Column('buyer_phone', sa.String(length=15), nullable=True),
    sa.Column('buyer_email', sa.String(length=100), nullable=True),
    sa.Column('buyer_logo', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False, comment='True if IGST applicable, False if CGST+SGST'),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='GST rate percentage (e.g., 18.00 for 18%)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_file', sa.String(length=500), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('idx_invoice_type', 'invoices', ['invoice_type'], unique=False)
    op.create_index('idx_invoice_user_created', 'invoices', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_type'), 'invoices', ['invoice_type'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False, comment='S.No. in the invoice'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_sac', sa.String(length=15), nullable=False, comment='HSN (goods) or SAC (services) code'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_item_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_index('idx_invoice_item_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_type'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index('idx_invoice_user_created', table_name='invoices')
    op.drop_index('idx_invoice_type', table_name='invoices')
    op.drop_index('idx_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_invoice_number_sequences_id'), table_name='invoice_number_sequences')
    op.drop_table('invoice_number_sequences')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
