"""
Django settings for invoice_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fn)be8+$8x*9hx5byt*775v==v_xc3h=%l)lr((r%+d470ljit'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'invoices',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invoice_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invoice_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # For development
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
}

# CORS settings for development
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    'http://localhost:3002',
    'http://127.0.0.1:3002',
]

CORS_ALLOW_CREDENTIALS = True

# For development, allow all hosts
ALLOWED_HOSTS = ['*']

# Email configuration - SMTP (Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sanjeevsriramsg@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'hcgjgurtfmoeadcm'  # Gmail App Password
DEFAULT_FROM_EMAIL = 'sanjeevsriramsg@gmail.com'

# For development/testing (prints to console instead of sending):
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# IMPORTANT: After generating App Password from Google:
# 1. Copy the 16-character password (it will have spaces like: xxxx xxxx xxxx xxxx)
# 2. Remove all spaces and paste here: EMAIL_HOST_PASSWORD = 'xxxxyyyyzzzzwwww'
# 3. Keep it inside quotes
# Example: EMAIL_HOST_PASSWORD = 'abcdefghijklmnop'

# Twilio Configuration for WhatsApp
# Get these from: https://console.twilio.com/
TWILIO_ACCOUNT_SID = ''  # Set this in production
TWILIO_AUTH_TOKEN = ''   # Set this in production
TWILIO_WHATSAPP_FROM = 'whatsapp:+14155238886'  # Twilio Sandbox number (or your approved number)

# Invoice settings
INVOICE_SETTINGS = {
    'TOPMATE_COMPANY_NAME': 'Topmate Technologies Pvt Ltd',
    'TOPMATE_GSTIN': '29AAFCT0123A1Z5',
    'TOPMATE_ADDRESS': '123 Business Park, HSR Layout, Bangalore, Karnataka',
    'TOPMATE_PINCODE': '560102',
    'TOPMATE_STATE': 'Karnataka',
    'TOPMATE_STATE_CODE': '29',
    'TOPMATE_PHONE': '+91 8012345678',
    'TOPMATE_EMAIL': 'invoices@topmate.io',

    # GST rates
    'GST_RATE': 18,  # 18% total (9% CGST + 9% SGST or 18% IGST)
    'CGST_RATE': 9,
    'SGST_RATE': 9,
    'IGST_RATE': 18,

    # Invoice prefixes
    'TOPMATE_INVOICE_PREFIX': 'TM-INV',
    'USER_INVOICE_PREFIX': 'USER',
}
