# Generated by Django 4.2.8 on 2025-12-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='hsn_sac',
            field=models.CharField(help_text='HSN (goods) or SAC (services) code', max_length=15),
        ),
    ]
